### PR TITLE
Caching Carthage directory on Travis

### PR DESCRIPTION
**Pull request by marekcirkos**
This should improve build and testing time

### CODE REVIEW

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3821103) to review internal test results.

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3821103) to review internal test results.

**Pull request closed without merging**
