### PR TITLE
Add way to use XCTest typing method

### PR DESCRIPTION
**Pull request by imurchie**

### CODE REVIEW

**Comment by imurchie** [comment]
Whoops. This is a work in progress. Ignore.

**Comment by marekcirkos** [comment]
@imurchie Just curious, what are you working on?

**Comment by jlipps** [comment]
We've noticed that WDA goes away or crashes on some systems (perhaps low-resource systems) when using send keys. @imurchie is working on a different way to set text that doesn't have this adverse side effect.

**Comment by imurchie** [comment]
Yes. This is work in progress to try to alleviate https://github.com/facebook/WebDriverAgent/issues/481 which I have tracked down to the [typing](https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBKeyboard.m#L33). I'm essentially trying out `XCUIElement` method `typeText`. Seems to work except in some situations things are typed too fast and the gestures run into each other and fail.

**Pull request closed without merging**
