### PR TITLE
Added WebDriverAgent that works with XCUITest framework

### PR DESCRIPTION
**Pull request by marekcirkos**

### CODE REVIEW

**Comment by ericwengelking** [comment]
@marekcirkos Is there any documentation on how to run WebDriverAgent using FBXCTWebDriverAgent instead of FBUIAWebDriverAgent?  By following the instructions in the Readme.md file I can get WebDriverAgent running with FBUIAWebDriverAgent.  I can run a command such as http://localhost:8100/tree with the UIA agent.  I'd like to start exploring what commands are available and what responses look like with the FBXCTWebDriverAgent.  Any help would be appreciated.

**Comment by marekcirkos** [comment]
Sorry for that, will add docs soon. Till then you can use xcodebuild or Xcode to start XCTUITestRunner by running test in UITestingUITests. It will start simulator with running  WebDriverAgent. All you need to do is start new session. To do this check this command https://github.com/facebook/WebDriverAgent/blob/XCUITest-WDACore/XCTWebDriverAgentLib/Commands/FBSessionCommands.m#L26

**Comment by ericwengelking** [comment]
For me when I run the tests the XCTStubApp crashes in main.m line 15. 

```obj-c
int main(int argc, char * argv[])
{
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([FBUIAppDelegate class]));
  }
}
```
I'm using Xcode 7.1 with an iOS 9.1 6s simulator.

**Comment by marekcirkos** [comment]
@ericwengelking I updated README. Are still having an issue starting XCTWebDriverAgent?

**Comment by mmmulani** [comment]
mega change but lgtm!

**Comment by ericwengelking** [comment]
No longer having issues after pulling the latest from master @marekcirkos .  Thanks for this and the updated Readme!

**Pull request merged**
