### PR TITLE
Unit tests for FBCacheTests

### PR DESCRIPTION
**Pull request by marekcirkos**

### CODE REVIEW

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1759048504308158/int_phab) to review.

**Comment by facebook-github-bot-4** [comment]
@marekcirkos updated the pull request.

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1759048504308158/int_phab) to review.

**Pull request closed without merging**
