### PR TITLE
Forward NSKeyValueObserverRegistration methods to proxied object

### PR DESCRIPTION
**Pull request by fr0l**
Add forwarding of NSKeyValueObserverRegistration methods.

Fixes issue #975 (Forward KVC-compliant methods to proxied object)

### CODE REVIEW

**Comment by marekcirkos** [comment]
Thank you!

**Comment by fr0l** [comment]
@marekcirkos this fix raises need to implement forwarding of methods in protocol NSKeyValueCoding
:-)

**Comment by fr0l** [comment]
It looks like better approach would be to subclass from NSProxy . I'll try that in a moment

**Comment by marekcirkos** [comment]
Why close?

**Comment by fr0l** [comment]
This PR opens need for need to implement some methods from ```NSKeyValueCoding```  protocol (for example ```valueForUndefinedKey```). I think probably the solution not to bodge here and there would be to use ```NSProxy``` as base class for ```FBApplicationProcessProxy```

but that would require a bit more code. but it's a more generic solution.

sorry I was too quick to open this PR (facepalm)

**Pull request closed without merging**
