### PR TITLE
fix typo in /source endpoint

### PR DESCRIPTION
**Pull request by Jonahss**

### CODE REVIEW

**Comment by mmmulani** [comment]
thanks for catching this :)

is the CLA stuff all good though or should I poke someone internally about that bot not working?

**Comment by Jonahss** [comment]
It *should* be good. I filled out the corporate one and not the individual one. Should I just fill out the individual one as well?

**Comment by mmmulani** [comment]
yea go for it

**Comment by Jonahss** [comment]
done.

**Pull request merged**
