### PR TITLE
Removed xcpretty-travis-formatter

### PR DESCRIPTION
**Pull request by marekcirkos**
This formatter nicely folds test section etc, however it also swallows any test error, which is not really helpful.

### CODE REVIEW

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-6** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3755048) to review internal test results.

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3755048) to review internal test results.

**Pull request closed without merging**
