### PR TITLE
Silence unguarded availability warning from Xcode 8.3

### PR DESCRIPTION
**Pull request by michaelpetrov**
Silence unguarded availability warning that appeared in Xcode 8.3 when importing `<XCTest/XCTest.h>`.

This allows WDA to compile by silencing the following error:
```
While building module 'XCTest' imported from WebDriverAgent/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.h:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCTest.h:57:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIDevice.h:50:22: error: 'XCUISiriService' is partial: introduced in iOS 10.3 [-Werror,-Wunguarded-availability]
@property (readonly) XCUISiriService *siriService NS_AVAILABLE_IOS(10_3);
                     ^
While building module 'XCTest' imported from WebDriverAgent/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.h:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCTest.h:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIDevice.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUISiriService.h:17:12: note: 'XCUISiriService' has been explicitly marked partial here
@interface XCUISiriService : NSObject
           ^
While building module 'XCTest' imported from WebDriverAgent/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.h:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCTest.h:57:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIDevice.h:50:22: note: explicitly redeclare 'XCUISiriService' to silence this warning
@property (readonly) XCUISiriService *siriService NS_AVAILABLE_IOS(10_3);
                     ^
1 error generated.
In file included from WebDriverAgent/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.m:10:
WebDriverAgent/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.h:10:9: fatal error: could not build module 'XCTest'
#import <XCTest/XCTest.h>
 ~~~~~~~^
2 errors generated.

```

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@michaelpetrov It seems like the change breaks compilation under Xcode <=8.2

https://travis-ci.org/facebook/WebDriverAgent/jobs/215790385
```
error: unknown warning option '-Wno-unguarded-availability'; did you mean '-Wno-partial-availability'? [-Werror,-Wunknown-warning-option]
```

Also the [doc here](https://reviews.llvm.org/D23003) confirms it is just an alias to _no-partial-availability_

**Comment by michaelpetrov** [comment]
I'll try it out with `no-partial-availability` on both 8.2 and 8.3, will update the diff if both compile.

**Comment by mykola-mokhnach** [comment]
This looks much better now. Can you please squash it?

**Comment by JaniJegoroff** [comment]
@mykola-mokhnach Roughly, how long (hours, days) patches usually would take time to land to the Appium 1.6.4-beta? Just wondering if I should wait or apply workaround temporarily in my environments.

**Comment by mykola-mokhnach** [comment]
@JaniJegoroff 

> apply workaround temporarily in my environments.

Just do it. I personally don't decide decide when and which stuff is released in Appium, but rather can only give advices. You could join Appium->general channel in Slack and ask there.

**Comment by michaelpetrov** [comment]
Here is the squashed commit of this change, please merge when you can. Thanks!

**Comment by mykola-mokhnach** [comment]
@michaelpetrov Unfortunately I cannot merge it. Only @marekcirkos can.

BTW for users who use WDA as Appium component. This [PR](https://github.com/appium/appium-xcuitest-driver/issues/407) is going to solve compiling issue there. It has been already approved and is going to be deployed in beta very soon.

**Comment by marekcirkos** [comment]
@michaelpetrov Thanks for your support ! :)

**Pull request closed without merging**
