### PR TITLE
Added Simulator Touch ID Match and NoMatch commands

### PR DESCRIPTION
**Pull request by kaleposhobios**
FBTouchIDCommands contains new route /simulator/touch_id with argument “match” to trigger Touch ID Match or NoMatch event

### CODE REVIEW

**Comment by kaleposhobios** [comment]
Note: this is a re-working of the previous PR https://github.com/facebook/WebDriverAgent/pull/92, so its cleaner and doesn't have Pods.

**Comment by marekcirkos** [comment]
I see you added it to UIAutomation WebDriverAgent does it work only on UIAutomation?
If it works for both UIAutomation and XCUITest could you move files to 'WebDriverAgentCore/Commands'?

**Comment by kaleposhobios** [comment]
Hi,

Thanks for taking a look. I didn't actually try it on UIAutomation, only on XCUITest. I put it in the location as suggested by mmmulani on this thread: https://github.com/facebook/WebDriverAgent/issues/26 but probably I didn't accurately communicate which mechanism it works with.

Since it's a just a notification posted to the system I'll move it to ```WebDriverAgentCore/Commands```

**Comment by kaleposhobios** [comment]
Ok, I have moved it. Please let me know if there's anything else I can do.

**Comment by marekcirkos** [comment]
Awesome, thank you!

**Comment by marekcirkos** [comment]
I needed to revert your diff due to issues with our, bot. They have been merged back here https://github.com/facebook/WebDriverAgent/commit/fa239bdea378b1030627d95f8e8fe60e69c19863

**Pull request merged**
