### PR TITLE
Add XCTHelper framework

### PR DESCRIPTION
**Pull request by bootstraponline**
#86

I'm new to Objective C so if there are any issues, let me know.

The code compiles. I don't think there are E2E tests to verify the helper code works.

### CODE REVIEW

**Comment by marekcirkos** [comment]
I don't think it make sense to extract everything to separate framework. Extracting 'utilities' to separate classes within WebDriverAgent library would be enough, as linker will pull only used classes.

**Comment by bootstraponline** [comment]
Ok, will update.

**Comment by bootstraponline** [comment]
I'll submit a new PR once updated.

**Comment by marekcirkos** [comment]
I'll be moving most of the code in that manner for better testability, so you can wait or help :)

**Comment by bootstraponline** [comment]
Cool. I might wait then. I'm currently working on some non-automation projects and will be back to iOS in a few weeks.

**Pull request closed without merging**
