### PR TITLE
Passing status code to Travis

### PR DESCRIPTION
**Pull request by marekcirkos**
Travis uses status codes to determine if the build has failed.

### CODE REVIEW

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-3** [comment]
@marekcirkos updated the pull request.

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/140170836419131/int_phab) to review internal test results.

**Comment by facebook-github-bot-2** [comment]
@marekcirkos updated the pull request.

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/140170836419131/int_phab) to review internal test results.

**Pull request closed without merging**
