### PR TITLE
Change iPad used for integration tests to iPad 2

### PR DESCRIPTION
**Pull request by marekcirkos**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
@marekcirkos updated the pull request.

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-8** [comment]
Thanks for importing.

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3669325) to review internal test results.

**Comment by facebook-github-bot-9** [comment]
@marekcirkos updated the pull request.

**Comment by marekcirkos** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3669325) to review internal test results.

**Pull request closed without merging**
