### PR TITLE
Removed old visibility check

### PR DESCRIPTION
**Pull request by marekcirkos**
New visibility check seems to be good enough, so removing old one.

### CODE REVIEW

**Comment by marekcirkos** [comment]
@mykola-mokhnach Do you guys still care about this or you are happy to remove it?

**Comment by mykola-mokhnach** [comment]
We have a special capability to use the alternative visibility detection method in Appium, but I have only seen 2 or 3 situations where we advised to use it. @imurchie what do you think, do we still need it?

**Comment by imurchie** [comment]
iOS 9.3 does not work at all using the new method, so yes.

**Comment by marekcirkos** [comment]
@imurchie It doesn't work because it is wrong or it crashes?

**Comment by marekcirkos** [comment]
https://github.com/imurchie?

**Comment by imurchie** [comment]
It always returns "true", if memory serves me correctly. Scrolling and stuff doesn't work because all elements are considered to already be on screen.

**Comment by marekcirkos** [comment]
Eh, that's a shame. Ok I'll drop it for now, so that we don't cause you too much trouble. :)

**Comment by imurchie** [comment]
Our plan is to drop iOS 9 support once iOS 11 is released for real. On our end there is a tonne that is needed for iOS 9 support (including supporting Instruments) so we are happy about this.

**Pull request closed without merging**
